@startuml Register

mainframe **flow** REGISTER

participant "DNS Client" as DNSC
participant "DNS Server" as DNSS

skinparam style strictuml
hide footbox

DNSC --> DNSS : Send REGISTER\n(name, port, ttl)
activate DNSS

alt Success
  DNSS --> DNSC : Send Record\n(name, ip, port, expires_at)
  note right: IP diambil dari alamat pengirim
else Failed
  DNSS --> DNSC : Send Error
  deactivate DNSS
end

@enduml